CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL
);

-- Optional sample data
INSERT INTO CATEGORY VALUES (1, 'Painkiller');
INSERT INTO CATEGORY VALUES (2, 'Antibiotic');
INSERT INTO CATEGORY VALUES (3, 'Vitamin');
INSERT INTO CATEGORY VALUES (4, 'Antiseptic');
