-- Create Suppliers Table
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CONTACT_NUMBER VARCHAR2(20),
    EMAIL VARCHAR2(100) 
);

-- Create Medicines Table
CREATE TABLE MEDICINES (
    MEDICINE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    QUANTITY NUMBER NOT NULL,
    REORDER_LEVEL NUMBER NOT NULL,
    SUPPLIER_ID NUMBER,
    CONSTRAINT FK_SUPPLIER FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS (SUPPLIER_ID)
);

-- Create Alerts Table
CREATE TABLE ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    MEDICINE_ID NUMBER NOT NULL,
    ALERT_TYPE VARCHAR2(50) NOT NULL,
    ALERT_MESSAGE VARCHAR2(200),
    ALERT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ALERT_MED FOREIGN KEY (MEDICINE_ID)
        REFERENCES MEDICINES (MEDICINE_ID)
);
