CREATE TABLE EXPIRY_ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    MEDICINE_ID NUMBER NOT NULL,
    ALERT_MESSAGE VARCHAR2(255),
    ALERT_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT fk_alert_medicine
        FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(ID)
);
