CREATE TABLE PURCHASE (
    PURCHASE_ID NUMBER PRIMARY KEY,
    MEDICINE_ID NUMBER NOT NULL,
    SUPPLIER_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PURCHASE_DATE DATE NOT NULL,

    CONSTRAINT fk_purchase_medicine 
        FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(ID),

    CONSTRAINT fk_purchase_supplier 
        FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);
